blank_issues_enabled: true
contact_links:
  - name: 🤔 Long question or ideas?
    url: https://github.com/INeedJobToStartWork/FluidUI/discussions
    about: Ask long-form questions and discuss ideas.
  - name: 💬 Discord Community Chat
    url: https://discord.gg/dCAkHxQ6hk
    about: Ask quick questions or simply chat on the `FluidUI` community Discord server.
