name: "📘 Docs issues"
title: "📘 [issue] - <TITLE_OF_ISSUE>"
description: Create new report!
labels: [issue]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug to FluiUI! 🙏

        This report section is for reporting issues with the documentation. If you have a question about how to achieve something and are struggling, please post a question


        If you have a question about how to achieve something and are struggling, please post a question
        inside of either of the following places:
          - FluidUI's 💬[Discussion's tab](https://github.com/INeedJobToStartWork/FluidUI/discussions)
          - FluidUI's 🤖[Discord channel](https://discord.gg/dCAkHxQ6hk)

        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
          - FluidUI's [Issue's tab]()
          - FluidUI's [closed issues tab]()
          - FluidUI's [Discussions tab]()


        Please fill in as much of the template below as you're able. If you don't know the answer to a question, that's okay, but please try to fill in as much as you can.
        It'll help us to triage your issue as quickly as possible.

  - type: input
    id: page
    attributes:
      label: Related page
      description: Which page is this issue related to?
      placeholder: e.g  https://fluidui.aimweb.dev/docs/
    validations:
      required: true

  - type: dropdown
    id: issue
    attributes:
      label: Kind of issue
      description: What kind of issue it is?
      multiple: true
      options:
        - "Unclear explanations"
        - "Missing information"
        - "Wrong information"
        - "Broken demo"
        - "Other"

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please give a short description of the issue

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why did you come to this page? What were you trying to do?
      value: |
        I was trying to..., i come to this page because...

  - type: dropdown
    id: role
    attributes:
      label: Who would be useful?
      description: Issue would be realted to?
      multiple: true
      options:
        - "Design"
        - "Video Editor / Creator"
        - "Programmer"
        - "Translator"

  - type: dropdown
    id: rate
    attributes:
      label: Scale of problem
      description: How annoying is this issue?
      multiple: true
      options:
        - "1 - Not annoying"
        - "2 - A little annoying"
        - "3 - Annoying"
        - "4 - Very annoying"
        - "5 - Extremely annoying"
        - "6 - Unbearable"
